import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import { ReactQueryProvider } from "@/providers/QueryClientProvider";
import ReduxProvider from "@/redux/store/provider";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Log Manager",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>{children}</ReduxProvider>
        {/* <ReactQueryProvider>{children}</ReactQueryProvider> */}
      </body>
    </html>
  );
}
