version: '3'
services:
  backend:
    build: ./go-server
    environment:
      - PORT=5000 
    deploy:
      replicas: 3
    networks:
      - loadbalancing

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - loadbalancing
    depends_on:
      - backend

networks:
  loadbalancing: